In [26]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_csv("user_fake_authentic_2class.csv")

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65326 entries, 0 to 65325
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   pos     65326 non-null  int64
 1   flw     65326 non-null  int64
 2   flg     65326 non-null  int64
 3   bl      65326 non-null  int64
 4   pic     65326 non-null  int64
 5   lin     65326 non-null  int64
 6   cl      65326 non-null  int64
 7   cz      65326 non-null  float64
 8   ni      65326 non-null  float64
 9   erl     65326 non-null  float64
 10  erc     65326 non-null  float64
 11  lt      65326 non-null  float64
 12  hc      65326 non-null  float64
 13  pr      65326 non-null  float64
 14  fo      65326 non-null  float64
 15  cs      65326 non-null  float64
 16  pi      65326 non-null  float64
 17  class   65326 non-null  object
dtypes: float64(10), int64(7), object(1)
memory usage: 9.0+ MB

In [29]:
df.isnull().sum()

pos      0
flw      0
flg      0
bl       0
pic      0
lin      0
cl       0
cz       0
ni       0
erl      0
erc      0
lt       0
hc       0
pr       0
fo       0
cs       0
pi       0
class    0
dtype: int64

In [30]:
df.describe()

,pos,flw,flg,bl,pic,lin,cl,cz,ni,erl,erc,lt,hc,pr,fo,cs,pi
count,65326.000000,6.532600e+04,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000,65326.000000
mean,176.571227,1.183077e+03,2310.519211,57.497061,0.951765,0.281925,136.520344,0.250012,0.193229,19.146641,1.139421,0.208877,0.507796,0.032745,0.052837,0.299098,496.475193
std,723.470655,2.170802e+04,2592.096104,64.129260,0.214264,0.449940,215.714486,0.337891,0.252939,121.047570,5.810627,0.300362,1.156921,0.220987,0.519058,0.349604,944.905389
min,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.000000,1.230000e+02,394.000000,0.000000,1.000000,0.000000,8.000000,0.000000,0.000000,2.730000,0.080000,0.000000,0.000000,0.000000,0.000000,0.033327,24.571458
50%,30.000000,3.380000e+02,995.000000,32.000000,1.000000,0.000000,46.000000,0.055556,0.059000,9.450000,0.440000,0.000000,0.077000,0.000000,0.000000,0.136915,183.227943
75%,124.000000,8.170000e+02,3600.000000,110.000000,1.000000,1.000000,170.000000,0.444444,0.333000,18.680000,1.040000,0.333000,0.611000,0.000000,0.000000,0.456342,580.771927
max,76200.000000,3.900000e+06,8800.000000,555.000000,1.000000,1.000000,3644.000000,1.000000,1.000000,26650.000000,1009.090027,1.000000,30.000000,20.000000,58.000000,1.000000,26786.134766

In [31]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['class'] = le.fit_transform(df['class'])

print(df['class'].value_counts())
print(le.classes_)

class
0    32866
1    32460
Name: count, dtype: int64
['f' 'r']

In [32]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 1082

In [33]:
for col in df.columns:
    if (df[col] < 0).any():
        print(col, df[col].min())

cl -1

In [34]:
duplicate_rows = df[df.duplicated(keep=False)]

print("Duplicated rows count:", len(duplicate_rows))

Duplicated rows count: 1460

In [35]:
print("Count of -1:", (df['cl'] == -1).sum())
print("Percentage:", ((df['cl'] == -1).sum()/len(df))*100)

Count of -1: 162
Percentage: 0.24798701895110678

In [36]:
duplicate_rows = df[df.duplicated(keep=False)]

print(
    duplicate_rows.groupby(list(df.columns))
    .size()
    .sort_values(ascending=False)
    .head(10)
)

pos  flw  flg   bl  pic  lin  cl  cz   ni   erl  erc  lt   hc   pr   fo   cs   pi   class
0    0    0     0   0    0    -1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0        162
                    1    0     0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0         37
          77    0   1    0     0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0         22
          73    0   1    0     0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0         14
          78    0   1    0     0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0         13
     56   6400  0   0    0     0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0         12
     0    79    0   1    0     0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0         12
          76    0   1    0     0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0         12
          75    0   1    0     0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0         11
     55   6400  0   0    0     0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0         11
dtype: int64

In [37]:
df['cl'] = df['cl'].replace(-1, 0)

df = df.drop_duplicates()

In [38]:
print(df.shape)
print(df.duplicated().sum())

(64244, 18)
0

In [39]:
from sklearn.model_selection import train_test_split

X = df.drop('class', axis=1)
y = df['class']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("\nTrain Labels:")
print(y_train.value_counts())

print("\nTest Labels:")
print(y_test.value_counts())

X_train: (51395, 17)
X_test : (12849, 17)

Train Labels:
class
1    25968
0    25427
Name: count, dtype: int64

Test Labels:
class
1    6492
0    6357
Name: count, dtype: int64

In [40]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [41]:
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:,1]

In [42]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_prob))

Accuracy : 0.8998365631566659
Precision: 0.8618100931461142
Recall   : 0.9548675292667899
F1 Score : 0.9059554256485203
ROC AUC  : 0.9608808595489702

In [43]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[5363  994]
 [ 293 6199]]

In [44]:
import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print(feature_importance)

   Feature  Importance
2      flg    0.165611
5      lin    0.157564
10     erc    0.147697
9      erl    0.120791
1      flw    0.062575
3       bl    0.056101
11      lt    0.045215
16      pi    0.043367
6       cl    0.041267
0      pos    0.038441
15      cs    0.031632
7       cz    0.026187
12      hc    0.018409
13      pr    0.017009
8       ni    0.016272
14      fo    0.010682
4      pic    0.001182

In [45]:
feature_importance[feature_importance['Importance'] < 0.01]

  Feature  Importance
4     pic    0.001182

In [46]:
df = df.drop(columns=['pic'])

In [47]:
from sklearn.model_selection import train_test_split

X = df.drop('class', axis=1)
y = df['class']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("\nTrain Labels:")
print(y_train.value_counts())

print("\nTest Labels:")
print(y_test.value_counts())

X_train: (51395, 16)
X_test : (12849, 16)

Train Labels:
class
1    25968
0    25427
Name: count, dtype: int64

Test Labels:
class
1    6492
0    6357
Name: count, dtype: int64

In [48]:
from sklearn.ensemble import RandomForestClassifier

rf2 = RandomForestClassifier(
    n_estimators=200,
    max_depth=15,
    min_samples_split=20,
    min_samples_leaf=10,
    random_state=42,
    n_jobs=-1
)

rf2.fit(X_train, y_train)

RandomForestClassifier(max_depth=15, min_samples_leaf=10, min_samples_split=20,
                       n_estimators=200, n_jobs=-1, random_state=42)

In [49]:
train_pred2 = rf2.predict(X_train)
test_pred2 = rf2.predict(X_test)

from sklearn.metrics import accuracy_score

print("Train Accuracy:", accuracy_score(y_train, train_pred2))
print("Test Accuracy :", accuracy_score(y_test, test_pred2))

Train Accuracy: 0.9193890456270065
Test Accuracy : 0.8986691571328508

In [50]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

y_pred2 = rf2.predict(X_test)
y_prob2 = rf2.predict_proba(X_test)[:,1]

print("Accuracy :", accuracy_score(y_test, y_pred2))
print("Precision:", precision_score(y_test, y_pred2))
print("Recall   :", recall_score(y_test, y_pred2))
print("F1 Score :", f1_score(y_test, y_pred2))
print("ROC AUC  :", roc_auc_score(y_test, y_prob2))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred2))

Accuracy : 0.8986691571328508
Precision: 0.8514355362946913
Recall   : 0.968422674060382
F1 Score : 0.9061689247621793
ROC AUC  : 0.9623477488683934

Confusion Matrix:
[[5260 1097]
 [ 205 6287]]

In [51]:
import joblib

joblib.dump(rf2, "authenticity_model_v1.pkl")

['authenticity_model_v1.pkl']

In [52]:
feature_columns = list(X.columns)

joblib.dump(feature_columns, "authenticity_features.pkl")

['authenticity_features.pkl']

In [53]:
model_info = {
    "model": "RandomForestClassifier",
    "accuracy": 0.8987,
    "f1": 0.9061,
    "roc_auc": 0.9623,
    "target_mapping": {
        "0": "Fake",
        "1": "Real"
    }
}

joblib.dump(model_info, "authenticity_metadata.pkl")

['authenticity_metadata.pkl']